### PR TITLE
Update readme with features and specify graphicality.

### LINKED ISSUE #5: More info on README
From the README, I have no idea whether this is a GUI or console program, what platforms are supported other than Linux, or any features that distinguish it from any other editor. I don't know who it's meant for, or why you would want to use it over Vim/Emacs/Sublime/what have you.

### PR DESCRIPTION
**Pull request by ghost**
I updated the readme with a short features list explaining what the text editor can do, added some elaboration on what it is, and added a screenshot below the features list.

closes #5

### CODE REVIEW

**Comment by mackron** [comment]
Thanks for this, but I had to remove that sentence at the top because I can't be making comparisons to Atom and Sublime just yet. I know you said **_some_** of the features compare well, but in my experience people tend to misinterpret these kinds of things. I think it'd be unwise to be making any kind of comparison to any established editors until I get more features implemented.

Good idea putting a screenshot in there though. 👍

**Comment by ghost** [comment]
Thanks for the opportunity to contribute :)

Totally hear ya on the Atom/Sublime comparison at the moment :)

It says Linux and Mac "depdend" on GTK now though and now I can't stand reading it X_X

**Comment by mackron** [comment]
I'm pretty sure that's the correct grammar because it's referring to multiple objects rather than a singular object. It's unimportant nonetheless :)

**Comment by ararslan** [comment]
I think she means the typo of "depdend" instead of "depend."

**Comment by ghost** [comment]
yup, but it doesn't really matter

**Comment by mackron** [comment]
Wow, my brain just did not see that at all! Fixed, thanks.

**Pull request merged**
